apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-storage
  namespace: mailu-mailserver
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/mnt/mailu"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-storage2
  namespace: mailu-mailserver
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/mnt/mailu"
