apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: abed472011@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solver:
    - http01:
        ingress:
          class: nginx