apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/keep-alive: 'true'
spec:
  rules:
    - host: mawahib-abed.com
      http:
        paths:
          - path: /api/v1/q
            pathType: Prefix
            backend:
              service:
                name: query-srv
                port:
                  number: 4000
          - path: /api/v1/v
            pathType: Prefix
            backend:
              service:
                name: videos-srv
                port:
                  number: 4002
          - path: /api/v1/u
            pathType: Prefix
            backend:
              service:
                name: users-srv
                port:
                  number: 4001